# es_connection = {
#     "host": "10.98.100.109",
#     "port": 9200,
#     "user": "elastic",
#     "password": "juniper@123"
# }
ticket_db = {
    "host": "10.98.100.107",
    "port": 3306,
    "user": "juniper",
    "password": "juniper@123"
}
num_core = 4
pattern_dict = {'KB31709': 'LUCHIP.*Display trap-info logic not initialized',
'KB32155': 'Uninitialized Read Error',
'KB31743': 'LUCHIP\(\d*\) DDR\d VERIFY_RETRY_LIMIT of \d* exceeded',
'KB31715': 'LUCHIP.* IDMEM.*read error',
'KB31714': 'LUCHIP.*RD_NACK.*TOE Read',
'KB31713': 'Secondary PPE.*zone.*timeout',
'KB31708': 'SHARED LMEM errors require LUCHIP.*PPE.*disable',
'KB31740': 'TOE ERROR.*DETECTED IN PFE.*TOE LU Stats',
'KB32168': 'HOST LOOPBACK WEDGE DETECTED',
'KB32162': 'lmem data error',
'KB32163': 'lmem addr error',
'KB32143': 'Errors async xtxn error',
'KB32142': 'Errors sync xtxn error',
'KB31901': 'LUCHIP.* .*RMC .* Uncorrectable ECC .* EDMEM',
'KB31732': 'RamBIST:.*LU-CHIP.* BIST: Memory Error',
'KB31731': 'LUCHIP.*RMC.*Correctable ECC .* cnt .* syn .* EDMEM',
'KB31727': 'LUCHIP.*pio_handle.*pio_read_u64.*failed',
'KB31728': 'LUCHIP.*HASH INT Status FPM Error',
'KB31726': 'LUCHIP.*PPE.*CBO.*mismatch.*rd.*exp',
'KB31716': 'LUCHIP.*PPE.*Errors lmem data error',
'KB31711': 'RMC.*Uninitialized EDMEM.*Read',
'KB31706': 'LUCHIP.* PPE_.* Errors KMB.* parity error',
'KB30724': 'LUCHIP\(\d*\).*RMC .* Uncorrectable ECC.*0x6db6db6d6db6db6d @ 0x.* EDMEM',
'KB20390': 'Errors ucode data error',
'KB31591': 'MQCHIP.*FI Error-cell sent to reorder engine',
'KB31583': 'MQCHIP.*FI Enqueuing error.*type.*seq.*stream',
'KB31582': 'MQCHIP.*DDRIF WO Checksum Error',
'KB31569': 'MQCHIP.*DDRIF FO.*Checksum Error',
'KB31689': 'MQCHIP.*WI parity error detected when read from ibuf',
'KB31688': 'MQCHIP.*CPQ RLDRAM single bit ECC error.*bank.*addr',
'KB31599': 'MQCHIP.*CPQ RLDRAM double bit ECC error.*bank.*addr',
'KB31593': 'MQCHIP.*MALLOC Pre-Q Reference Count underflow.*decrement below zero',
'KB31584': 'MQCHIP.*CPQ Sram parity error, errlog',
'KB31581': 'MQCHIP.*FO Request time-out error',
'KB31568': 'MQCHIP.*FI Cell underflow at the state stage',
'KB31739': 'MQCHIP.*PT CPT parity error detected',
'KB31592': 'MQCHIP.*OCM Fo.*Ddrif Parity Error',
'KB32161': 'Errors KM.* parity error',
'KB32157': 'ucode sb data error',
'KB32156': 'gumem\[\d*\]\.par_protect',
'KB32158': 'Errors CBO.* parity error',
'KB32353': 'XL.*cass_xr.*dbuf_protect Corrected XR DBUF',
'KB32154': 'Double-bit ECC error',
'KB32153': 'idmem_slice.*Corrected single bit ECC error',
'KB32152': '(PRB_EVENERR|PRB_ODDERR)',
'KB32144': '(SECONDARY_TIMEOUT|PRIMARY_TIMEOUT)',
'KB32137': 'filter\.pf0_1.alpha\[\d*\]\.protect',
'KB31684': 'XMCHIP.*MALLOC.*DMEM allocation memory parity error',
'KB32105': 'XMCHIP.*DDRIF:.*LLISTQ.*Parity error for free pointer SRAM',
'KB31697': 'XMCHIP.*OCM: .*parity error - Parity Error Address',
'KB31696': 'XMCHIP.*MALLOC.*DREF memory parity error',
'KB31680': 'XMCHIP.*WI.*Input pause buffer exceeded.*Check if the transmitter respects pause frames',
'KB32171': 'XMCHIP.*Cell packing interface error',
'KB32106': 'PRECL.*XM_engine.*instmem parity error detected',
'KB32005': 'XMCHIP.*CPQ1.*Queue un.*run indication',
'KB31737': 'XMCHIP.*WO.*Packet error - Error Packets',
'KB31736': 'XMCHIP.*PT.*Protect.*Log Error.*Log Address.*Multiple Errors',
'KB31735': 'XMCHIP.*LI.*Received a parcel with more than 512B accompanying data',
'KB31734': 'XMCHIP.*FI.*Link sanity checks.*Type',
'KB31733': 'XMCHIP.*LI.*Received a parcel from the HSL2 interface with EOPE',
'KB31703': 'XMCHIP.*PT.*Missing SOP.*EOP errors from input blocks',
'KB31702': 'XMCHIP.*FI.*Packet CRC error',
'KB31701': 'XMCHIP.*DRD.*WAN parcel timeout error',
'KB31698': 'XMCHIP.*PT.*Protect.*Parity error for CPFIFO data memory',
'KB31687': 'XMCHIP.*DDRIF.*Checksum error for FO/WO.*Channel.*Address.*Checksum Errors',
'KB31686': 'XMCHIP.*FI.*Aliasing on allocates error.*Pipe count',
'KB31685': 'XMCHIP.*EPM.*upon free pool',
'KB31682': 'XMCHIP.*FO.*Request timeout error.*Number of timeouts',
'KB31681': 'XMCHIP.*XXLCE.*Port Interrupts.*Ethernet Rx Stats Parity Error',
'KB31679': 'XMCHIP.*LI.*Received cookie size different from expected',
'KB31619': 'XMCHIP.*DRD.*Protect.*Parity error for DRD memory',
'KB31617': 'XMCHIP.*DRD.*Fabric parcel timeout error',
'KB31609': 'XMCHIP.*Scheduler:.*Protect:.*Parity error for tick table single port SRAM',
'KB31610': 'XMCHIP.*FI.*Protect.*Parity error for .* freepool SRAM',
'KB31608': 'XMCHIP.*WI CPQ Free Pointer SRAM Protect:.*Parity error',
'KB31607': 'XMCHIP.*MALLOC:.*SChunk allocation memory parity error',
'KB31601': 'XMCHIP.*Scheduler.*Protect.*Parity error for TDM table single port SRAM',
'KB31600': 'XMCHIP.*DRD0.*Reference count memory decrement error.*PCT',
'KB31611': 'XMCHIP.*FI.*Cell underflow at the state stage',
'KB31602': 'XMCHIP.*DRD.*Command sequence error',
'KB37469': 'XMCHIP_CMERROR_DDRIF_PROTECT_LLISTQ_SRAM_CHNK_CHKSUM \(0x70068\)',
'KB32890': 'XMCHIP.*HOSTIF: Protect: Parity error for SRAM in bank.*',
'KB33994': 'MQSS.*WANIO_CR.*Parity error detected for Tx SRAM - detected_txlink',
'KB32085': 'MQSS.*FO.*Parity error detected for output buffer control',
'KB31717': 'MQSS.*FO: Request timeout error - Number of timeouts .*, RC select .*, Stream',
'KB31718': 'MQSS.*LI.*Unroll TAIL length overflow',
'KB31722': 'EA.*HMCIF Rx.*Link.*Response FIFO .* overflow',
'KB31694': 'EA.*HMCIF Rx.*Link.*HMCIF Rx retry attempts failed',
'KB31693': 'EA.*HMCIF Rx.*Link.*HMC token overflow',
'KB32090': 'MQSS.*BCMF CBUF.*Parity error corrected for buffer free list memory for bank',
'KB32335': 'EA.*Checksum error detected on',
'KB32342': 'MQSS.*FI.*Child drop error',
'KB32333': 'MQSS.*LI.*Received a parcel with more than 512B accompanying data',
'KB32352': 'MQSS.*DRD.*CMD FSM state error',
'KB32343': 'MQSS.*FI.*Cell jump drop error',
'KB32334': 'MQSS.*Cell packing interface error',
'KB32291': 'EA.*HMCIO TX: AFIFO overflow event detected in Channel',
'KB32332': 'EA.*HMCIO RX: SFIFO overflow event detected in Channel',
'KB32119': 'HMM.*Lane.*TX RLL event',
'KB32087': 'EA.*Bist XRIF.*failed',
'KB32084': 'MQSS.*BCMW ICM.*Invalid cell sequence.*Packet start without SOP or 16K packet bytes without SOP',
'KB32088': 'MQSS.*FI.*Parity error detected for bank.*of CP table',
'KB32089': 'EA.*reports CM err HMC BIST has detected error',
'KB31720': 'MQSS.* FI: Cell underflow at the state stage \(Cell behind reorder window\) - Stream .* Count .*',
'KB31723': 'EA.*HMCIF.*HMCIF has no chunk index available for incoming WO read',
'KB31719': 'MQSS.*DRD.*Protect.*Parity error corrected for alloc state memory .* data32_log_err .* data32_log_address',
'KB31721': 'MQSS.*BCMF CBUF.*SRAM Protect.*Parity error detected for Bank.*Sub-Bank.*memory',
'KB31695': 'total number of corrected singlebit errors from HMC 1 exceeded threshold \d\d\d\d',
'KB31692': '.*CPQW Fast request is asserted for empty Queue',
'KB31691': 'CPQW Freelist Manager run out of avaliable fl pointers',
'KB31690': 'Qdepth underrun error in Drop engine',
'KB32344': '.*response packet with a FATAL state is received from HMC - State: 0x1f, Count',
'KB32091': '.*response packet with a FATAL state is received from HMC - State: 0x7f, Count',
'KB37050': '.*ECC single bit parity error',
'KB35999': 'PHY stream.*to drain',
'KB34996': 'exited on signal.*|.*clock failure',
'KB37507': 'ECC Protect: Parity error corrected for FlexMem slices',
'TSB74336':'(Machine check events loggedkernel.*Machine check events logged|CPU_CMERROR_DDR_CORRECTABLE_MINOR)',
'KB37331': 'TPCI PIO Read errors seen in last second',
'KB30474': 'CHASSISD_I2CS_READBACK_ERROR: Readback error from I2C slave for FPC',
'KB78259': 'FI: Cell underflow errors with reorder engine pointers stalled',
'KB78191': 'XQSS_CMERROR_CPQW_ERR_INT_FSET_LP_RD_ERR',
'KB72383': 'LUCHIP.*LKUP_ASIC_SINGLE_BIT_ECC',
'KB70778': 'MQSS.*: DRD.* Protect: Multiple Errors',
'KB77691': 'LKUP_ASIC_HSL2_MAJOR_CRC_ERROR',
'KB77156': 'MQSS_CMERROR_DRD_UNROLL_SRAM_PAR_PROTECT_FSET_REG_DETECTED_TO_CPQW_FIFO_LOW',
'KB77455': 'MQSS_CMERROR_MALLOC_SRAM_ECC_PROTECT_FSET_REG_CORRECTED_ALLOC_PFB_MEM0',
'KB76334': 'MQSS_CMERROR_FO_MEM_PAR_PROTECT_FSET_REG_DETECTED_OBUF_DATA',
'KB77470': 'MQSS_CMERROR_DRD_TOP_ECC2_PROTECT_FSET_REG_CORRECTED_FL_FIFO_MEM0',
'KB76675': 'EACHIP_CMERROR_HMCIF_RX_ECC1_PROTECT_FSET_REG_CORRECTED_FO_CHKSUM_IDX',
'KB72915': 'MQSS.* FI: Protect: Parity error detected for timer SRAM',
'KB75988': 'XMCHIP.*: XMCHIP.*: DRD.*: Command sequence error',
'KB75209': 'FI_PROTECT: .* Parity error for .* Freepool SRAM',
'KB75103': 'MQSS_CMERROR_CPQF_SRAM_PAR_PROTECT_FSET_REG_DETECTED_PFBE',
'KB70266': 'EACHIP_CMERROR_XIF_MQSS_PAR_PROTECT_FSET_REG_DETECTED_OCM',
'KB74110': 'MQSS.*: MQSS.*: BCMW ICM: RORD Protect: Parity error detected for .* memory - data32_log_err .* data32_log_address',
'KB35068': 'Restart FPC .* due to NMI timeout',
'KB36937': 'Parity error detected for the high portion of CPQW buffer',
'KB79298': 'CMERROR_PQ3_DDR_1_BIT_MINOR',
'KB35989': 'MQ Chip Error code: 0x3000',
'KB36840': 'BIOS Boot from secondary flash',
'KB81552': 'DSTAT_DBGMON_CLIENT_USEMETER',
'KB13562': 'PFE_NH_RESOLVE_THROTTLED',
'KB1580': 'UI_CLI_MMAP_INCREASE: could not extend cli automore memory',
'KB18836': 'CHASSISD_PIC_HWERROR',
'KB18999': 'SDRAM.* ECC error',
'KB19007': 'CCHIP.* abnormal discard seen',
'KB21730': 'mqchip_intx_interrupt_handler: MQ.* Reading the interrupt .* failed with error',
'KB24091': 'RPD_MPLS_OAM_LSP_PING_REPLY_ERR',
'KB24127': 'LIBJSNMP_NS_LOG_WARNING',
'KB27712': 'i2c access failure exceed .* disable periodic',
'KB28431': 'N+1 Power redundancy missing',
'KB29160': 'XMCHIP.* Scheduler: Protect: Parity error for tick table single port SRAM',
'KB29544': 'VSC8248 .* is running out-of-date firmware version',
'KB29635': 'xntpd.* setsockopt IP_MULTICAST_TTL fails on address .* Bad file descriptor',
'KB30817': 'rnh_index_alloc: Failing Invalid nexthop index allocation',
'KB30968': 'watchdog timeout -- resetting',
'KB31515': 'Offline uncorrectable sectors',
'KB31618': 'DDOS: Master socket closed',
'KB31707': 'LUCHIP.* PPE.*Zone.* is not bound to a context',
'KB31868': 'eventd.* Bad file descriptor',
'KB31870': 'fpc.* HALP-lbnh_xlate_cntr_db_show.* xlate Counter db not created',
'KB32477': 'ms.* Mounting 128.0.0.1:/var/tmp/pics on /var/re: mount_nfs failed/timed out',
'KB32478': 'xlchip_cassxr_hotbank_check CASS XR Heavy Bank Mask',
'KB32509': 'MIB2D_COUNTER_DECREASING: pfes_stats_delta: counter .* decreasing',
'KB32550': 'pmbus_read_volt: .* pmbus read failed for cmd',
'KB32551': 'BGP_WRITE_WOULD_BLOCK',
'KB32582': 'SNMP_EVLIB_FAILURE: PFED ran out of transfer credits with PFE',
'KB32688': 'RPD_RSVP_BYPASS_DOWN .* inactivity timeout',
'KB32732': 'pconn_server_send_ipc: failed to send message',
'KB32748': 'ifrt_ifl_update_vcp_ifl_rcv_pkt_cnt.* Didn\'t find ifl',
'KB32763': 'Heap memory utilization crossed .* Percent, reached to .* percent',
'KB32924': 'D4P.* FROML .* data path stuck',
'KB34491': 'interrupt storm detected on .* throttling interrupt source',
'KB35422': 'New CRC errors found on xfchip .* plane',
'KB35925': 'fpc.* HMC .* error',
'KB35971': 'fpc.* CMTFPC: Fabric request time out pfe .* plane .* attempting recovery',
'KB36192': 'QX-chip.* scheduler .* internal memory error',
'KB36242': 'XMCHIP.* EPM.* Packet delimiter violation detected',
'KB36879': 'PFED_NOTIF_GLOBAL_STAT_UNKNOWN: Unknown global notification stat: Parsed',
'KB74743': 'IXCHIP.*chan-rx.* read errors.crc_error.* failed',
'KB14186': 'RPD_OS_MEMHIGH',
'KB18750': 'ACCT_XFER_POPEN_FAIL',
'KB18760': 'AUTHD_AUTH_CREATE_FAILED',
'KB18765': 'AUTOCONFD_AUTH_NO_MEM',
'KB18772': 'BFDD_READ_ERROR',
'KB18773': 'BFDD_WRITE_ERROR',
'KB18778': 'CHASSISD_CLOCK_FAILURE',
'KB18779': 'CHASSISD_CMB_READBACK_ERROR',
'KB18780': 'CHASSISD_COMMAND_ACK_ERROR',
'KB18786': 'CHASSISD_FASIC_HSL_LINK_ERROR',
'KB18788': 'CHASSISD_FASIC_INPUT_DROP',
'KB18790': 'CHASSISD_FASIC_PIO_READ_ERROR',
'KB18791': 'CHASSISD_FASIC_PIO_WRITE_ERROR',
'KB18792': 'CHASSISD_FASIC_PLL_ERROR',
'KB18797': 'CHASSISD_FCHIP_HST_ERROR',
'KB18818': 'CHASSISD_I2C_BAD_IDEEPROM_FORMAT',
'KB18819': 'CHASSISD_I2C_READ_ERROR',
'KB18820': 'CHASSISD_I2CS_READBACK_ERROR',
'KB18823': 'CHASSISD_IPC_CONNECTION_DROPPED',
'KB18826': 'CHASSISD_IPC_MSG_UNHANDLED',
'KB18827': 'CHASSISD_IPC_WRITE_ERR_NULL_ARGS',
'KB18828': 'CHASSISD_MAC_ADDRESS_ERROR',
'KB18832': 'CHASSISD_OVER_TEMP_CONDITION',
'KB18833': 'CHASSISD_OVER_TEMP_SHUTDOWN_TIME',
'KB18834': 'CHASSISD_PEM_OVERLOAD',
'KB18835': 'CHASSISD_PEM_VOLTAGE',
'KB18836': 'CHASSISD_PIC_HWERROR',
'KB18837': 'CHASSISD_POWER_CHECK',
'KB18838': 'CHASSISD_PSU_ERROR',
'KB18839': 'CHASSISD_PSU_FAN_FAIL',
'KB18841': 'CHASSISD_PSU_OVERLOAD',
'KB18845': 'CHASSISD_RE_OVER_TEMP_SHUTDOWN',
'KB18846': 'CHASSISD_RE_OVER_TEMP_WARNING',
'KB18852': 'CHASSISD_TEMP_SENSOR_FAILURE',
'KB18853': 'CHASSISD_TIMER_VAL_ERR',
'KB18854': 'CHASSISD_UNEXPECTED_EXIT',
'KB18856': 'CHASSISD_VOLTAGE_SENSOR_INIT',
'KB18858': 'CONNECTION_CRAFTD_FAIL',
'KB18859': 'CONNECTION_RTLOGD_FAIL',
'KB18860': 'CONNECTION_SEND_ERROR',
'KB18863': 'COSD_RTSOCK_LIB_ERR',
'KB18866': 'COSD_UNKNOWN_TRANSLATION_TABLE',
'KB18867': 'Core dumped',
'KB18868': 'DCD_CONFIG_WRITE_FAILED',
'KB18875': 'DFCD_GENCFG_WRITE_FAILED',
'KB18876': 'DFCD_LINH_MALLOC_FAILED',
'KB18877': 'DFWD_CONFIG_WRITE_FAILED',
'KB18879': 'DFWD_PARSE_STATE_EMERGENCY',
'KB18880': 'DFWD_TRASHED_RED_ZONE',
'KB18884': 'DH_SVC_SOCKET_FAILURE',
'KB18892': 'EVENTD_FORK_ERR',
'KB18893': 'EVENTD_PIPE_ERR',
'KB18894': 'EVENTD_VERSION_MISMATCH',
'KB18895': 'FPCLOGIN_IP_ADDRESS_GET_FAILURE',
'KB18896': 'FSAD_ERROR',
'KB18897': 'FUD_MEMORY_ALLOCATION_FAILURE',
'KB18906': 'HNCACHED_PATRICIA_ERROR',
'KB18909': 'IDP_DAEMON_INIT_FAILED',
'KB18928': 'rdp retransmit error',
'KB18929': 'RT_PFE: NH IPC .* failed, err 6',
'KB18931': 'parity error detected, fll reinit: mpfe',
'KB18932': 'Process .* has exceeded .* of RLIMIT_DATA',
'KB18936': 'L2CPD_ABORT',
'KB18943': 'L2TPD_SERVER_START_FAILED',
'KB18950': 'LIBJNX_EXEC_SIGNALED',
'KB18951': 'LIBJNX_REPLICATE_RCP_ERROR',
'KB18952': 'LIBJNX_SNMP_ENGINE_FILE_FAILURE',
'KB18953': 'LIBJNX_SNMP_ENGINE_SCAN_FAILURE',
'KB18964': 'LIBSERVICED_SOCKET_BIND',
'KB18966': 'LICENSE_EXPIRED',
'KB18967': 'LICENSE_GRACE_PERIOD_APPROACHING',
'KB18968': 'LICENSE_GRACE_PERIOD_EXCEEDED',
'KB18970': 'LICENSE_NEARING_EXPIRY',
'KB18971': 'LLDPD_SYSTEM',
'KB18978': 'MIB2D_RTSLIB_READ_FAILURE',
'KB18979': 'MIB2D_SNMP_INDEX_ASSIGN',
'KB18980': 'MIB2D_SNMP_INDEX_DUPLICATE',
'KB18988': 'ichip_f_check_dest_errors',
'KB18991': 'BCHIP .* multiple correctable ECC errors',
'KB18992': 'PFE.* multiple uncorrectable ECC errors',
'KB18994': 'ASIC Initialization Error',
'KB18998': 'Packet drop in Ichip',
'KB19000': 'CCHIP.* SRAM parity error',
'KB19001': 'TOXIC SFP',
'KB19003': 'SHEAF: possible leak',
'KB19005': 'RT: Failed prefix change',
'KB19008': 'IA_PCIIF.* clock error',
'KB19011': 'ICHIP.* New illegal link errors in WO DESRD',
'KB19012': 'ICHIP.*New packet errors in WO HDRF, iwo_hdrf_poll_stats',
'KB19013': 'DDR SDRAM Error: Multi-bit ECC error',
'KB19016': 'SFP receive power low warning set',
'KB19019': 'ICHIP.*_REG_ERR:Non first cell drops in ichip',
'KB19022': 'PPMD_READ_ERROR',
'KB19024': 'Reboot reason\(s\): 0x2: watchdog',
'KB19030': 'SNMPD_RMON_EVENTLOG: ais_fpc_high_cpu_utilization',
'KB19049': 'RPD_ASSERT',
'KB19050': 'RPD_ASSERT_SOFT',
'KB19051': 'RPD_BGP_NEIGHBOR_STATE_CHANGED',
'KB19061': 'RPD_DYN_CFG_REGISTER_FAILED',
'KB19069': 'RPD_ISIS_OVERLOAD',
'KB19070': 'RPD_KRT_KERNEL_BAD_ROUTE',
'KB19071': 'RPD_KRT_Q_RETRIES',
'KB19072': 'RPD_LMP_UNEXPECTED_OPCODE',
'KB19074': 'RPD_OSPF_NBRDOWN',
'KB19091': 'SERVICED_COMMAND_FAILED',
'KB19093': 'SERVICED_EVENT_FAILED',
'KB19099': 'SERVICED_PID_FILE_UPDATE',
'KB19106': 'SNMP_PATRICIA_ERROR',
'KB19107': 'SNMP_RTSLIB_FAILURE',
'KB19109': 'SNMPD_RMONFILE_FAILURE',
'KB19110': 'SNMPD_SEND_FAILURE',
'KB19115': 'SPD_GEN_NUM_FAIL',
'KB19116': 'savecore: writing kernel to',
'KB19121': 'TASK_OS_MEMHIGH',
'KB19131': 'VRRPD_MISSING_VIP',
'KB19312': 'kernel: PCF8584\(WR\): \(i2c_s1=0x08, group=0xf,device=0x54\)',
'KB20741': 'ICHIP.*_REG_ERR:packet checksum error in input fab_stream .* pfe_id',
'KB20849': 'Loss of communication with Backup RE',
'KB21041': 'ICHIP.*_REG_ERR:first cell drops in ichip fi rord',
'KB21045': 'ICHIP.*_REG_ERR:.*Wi seg ucode discards in fabric stream .* pfe_id',
'KB21049': 'ICHIP.*_REG_ERR:.*',
'KB21054': 'ICHIP.*_REG_ERR:.*Wi seg packet ttl error in fabric stream .* pfe_id',
'KB21403': ' Unlist request: unilist\(nh index = .*\) found on the rnhlist_deleted_root patnode, hence returning',
'KB21943': 'CHASSISD_FRU_OFFLINE_NOTICE',
'KB22215': 'RT msg op .* \(PREFIX ADD\) failed, err',
'KB22373': 'RT-HAL,rt_entry_add_msg_check.* Duplicate pfx, proto .*, rtt index .* prefixlen .* prefix .* nh',
'KB23631': 'init: snmp .* terminated by signal number',
'KB24091': 'RPD_MPLS_OAM_LSP_PING_REPLY_ERR',
'KB24127': 'LIBJSNMP_NS_LOG_WARNING',
'KB24835': 'LIBJSNMP_NS_LOG_ERR',
'KB26140': 'CHASSISD_PEM_INPUT_BAD',
'KB26866': 'general-authentication-service .* terminated by signal number .* Core dumped',
'KB28398': 'fpm_atlas_acb_storm_state_change: acb storm active',
'KB29518': 'CHASSISD_SIGPIPE: SIGPIPE received',
'KB29642': 'UI_CHILD_SIGNALED',
'KB29671': 'CHASSISD_SNMP_TRAP6',
'KB30702': 'CMALARM: Error .* type:Major.* encountered',
'KB30725': 'ICHIP .* one or more stream blocked detected',
'KB31268': 'Alarm set: FPC color=RED, class=CHASSIS, reason=FPC .* Major Errors',
'KB31620': 'CHASSISD_SNMP_TRAP10',
'KB35986': 'Failed login attempts from host (ttyu0|\[unknown\])',
'KB37437': 'IGMP version mismatch',
}
data_path = "/var/tmp/for_unsupervised_report"
# MAX_SIZE_MB = 200
