specific_words = {
    'del': 'delete',
    'err': 'error',
    'pkt': 'packet',
    'nh': 'next hop',
    'aggr': 'aggregate',
    'ucast': 'unicast',
    'auth': 'authentication',
    'sendto': 'send to',
    'nh-id': 'next hop id',
    'obj': 'object',
    'dyn': 'dynamic',
    'phy': 'physical',
    'addr': 'address',
    'rev': 'revision',
    'msg': 'message',
    'var': 'variable',
    'diag': 'diagnostic',
    'kern': 'kernel',
    'sndcc': 'send buffer size in bytes',
    'rcvcc': 'receive buffer size in bytes',
    'snd': 'send',
    'una': 'unacknowledged',
    'nxt': 'next',
    'wnd': 'window',
    'rcv': 'receive',
    'adv': 'advertised',
    'hw': 'hardware',
    'tnl': 'tunnel',
    'exp': 'experimental',
    'dscp': 'differentiated services code point',
    'rt': 'route',
    'rtt': 'route trip time',
    'dc': 'destination class',
    'sc': 'source class',
    'rpf': 'reverse path forwarding',
    'cos': 'class of service',
    'dfw': 'dynamic firewall',
    'stat': 'statistic',
    'ctl': 'control',
    'h/w': 'hardware',
    'ptr': 'pointer',
    'qh': 'queue head',
    'conn': 'connection',
    'inactivesqtd': 'inactive sqtd',
    'param': 'parameter',
    'params': 'parameters',
    'recv': 'receive',
    'rnh': 'routing next hop',
    'ptp': 'precision time protocol',
    'rpm': 'Real Time Performance Monitoring',
    'rts': 'request to send',
    'proc': 'process',
    'idl': 'interconnect description language',
    'rtsock': 'routing socket',
    'intf': 'interface',
    'trans': 'transaction',
    'ifl': 'logical interface',
    'dfwdlib': 'dfwd library',
    'altnext': 'alternative next',
    'ifd': 'interface device',
    'sntpsync': 'simple network time protocol sync',
    'qtd': 'Queue Element Transfer Descriptor',
    'rtc': 'real time clock',
    'ch': 'channel',
    'serv': 'service',
    'idx': 'index',
    'ifp': 'ingress filter processor',
    'tcam': 'ternary content addressable memory',
    'ack': 'acknowledge',
    'NNI': 'network to network interface',
    'pw-ifl': 'pseudowire logical interface',
    'if_pfe': 'interface pfe',
    'ifstate': 'interface state',
    'chk': 'check',
    'fw': 'firewall',
    'ifdpointchange': 'interface device point change',
    'tlv': 'type length value',
    'fwd': 'forward',
    'len': 'length',
    'bundlestate': 'bundle state',
    'bd': 'bundle',
    'inact': 'inactive',
    'endpt': 'endpoint',
    'eps': 'event per second',
    'dtc': 'distributed transaction coordinator',
    'cfg': 'config',
    'cerr': 'content error',
    'tdm': 'time division multiplexing',
    'inst': 'instance',
    'intfs': 'interfaces',
    'errmsg': 'error message',
    'sw': 'switch',
    'src': 'source',
    'dst': 'destination',
    'cmlc': 'chassis manager line card',
    'pkts': 'packets',
    'res': 'resolution',
    'desc': 'description',
    'tx': 'tranѕmitter',
    'rx': 'receiᴠer',
    'nak': 'not acknowledged',
    'dma': 'direct memory access',
    'na': 'neighbour advertisement',
    'ns': 'neighbour solicitation',
    'cfm': 'connectivity fault management',
    'reg': 'register',
    'jnh': 'junos next hop',
    'prl': 'packet replication layer',
    'acct': 'accounting',
    'pam': 'pluggable authentication module',
    'sm': 'security module',
    'dfe': 'decision feedback equalizer',
    'fbuf': 'firewall buffer',
    'vc': 'virtual circuit',
    'bw': 'bandwidth',
    'req': 'request',
    'ql': 'quality level',
    'pwr': 'power',
    'num': 'number',
    'putblk': 'put block',
    'iftlv': 'interface type length value',
    'nlri': 'Network layer reachability information',
    'rhost': 'routing host',
    'sysctlbyname': 'system control by name',
    'mhop': 'multi hop',
    'krt': 'kernel routing table',
    'rttable': 'routing table',
    'ipt': 'ip table',
    'sec': 'secondary',
    'rtb': 'route table',
    'vrf': 'virtual routing forwarding',
    'setsockopt': 'set socket operation',
    'sched': 'scheduler',
    'dyncfg': 'dynamic configugration',
    'nbr': 'neighbour',
    'ifdev': 'interface device',
    'chan': 'channel',
    'lostconn': 'lost connection',
}
